<?php

/**
 * Implements hook_block_info().
 */
function bacchanight_block_info() {
  $blocks['current_posts'] = array(
    // The name that will appear in the block list.
    'info' => t('Bacchanight'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

function bacchanight_menu() {

    $items = array();

    $items['admin/config/content/bacchanight'] = array(
      'title' => 'Bacchanight',
      'description' => 'Configuration du module Bacchanight',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('bacchanight_form'),
      'access arguments' => array('access administration pages'),
      'type' => MENU_NORMAL_ITEM,
    );

    $items['bacchanight'] = array(
      'title' => 'Bacchanight',
      'description' => 'ffze',
      'page callback' => 'param_manager',
      'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    );
    return $items;
}


/**
 * Page callback: Bacchanight settings
 *
 * @see bacchanight_menu()
 */
function bacchanight_form($form, &$form_state) {

    $form['titre'] = array(
      '#type' => 'textfield',
      '#title' => t('Titre'),
      '#default_value' => variable_get('titre', "Bacchatitre"),
      '#size' => 50,
      '#maxlength' => 100,
      '#description' => t('Le titre de l\'évènement'),
      '#required' => TRUE,
    );


    $form['mail'] = array(
      '#type' => 'textfield',
      '#title' => t('Adresse mail'),
      '#default_value' => variable_get('mail', "Bacchamail@baccha.mail"),
      '#size' => 50,
      '#maxlength' => 100,
      '#description' => t('L\'adresse de contact de l\'évènement'),
      '#required' => TRUE,
    );

    $form['numero_telephone'] = array(
      '#tyafault_value' => variable_get('numero_telephone', "+33 "),
      '#size' => 50,
      '#maxlength' => 100,
      '#description' => t('Le numéro de téléphone de contact de l\'évènement'),
      '#required' => TRUE,
    );


  $form['adresse'] = array(
    '#type' => 'textfield',
    '#title' => t('Adresse'),
    '#default_value' => variable_get('adresse', "Baccarue"),
    '#size' => 50,
    '#maxlength' => 100,
    '#description' => t('Numéro et libellé de la rue'),
    '#required' => TRUE,
  );

  $form['zipcode'] = array(
    '#type' => 'textfield',
    '#title' => t('Code postal'),
    '#default_value' => variable_get('zipcode', '00000'),
    '#size' => 5,
    '#maxlength' => 5,
    '#description' => t('Le code postal'),
    '#required' => TRUE,
  );

  $form['ville'] = array(
    '#type' => 'textfield',
    '#title' => t('Ville'),
    '#default_value' => variable_get('ville', 'Orthez'),
    '#size' => 50,
    '#maxlength' => 100,
    '#description' => t('La ville'),
    '#required' => TRUE,
  );

  $form['pays'] = array(
    '#type' => 'textfield',
    '#title' => t('Pays'),
    '#default_value' => variable_get('pays', 'France'),
    '#size' => 50,
    '#maxlength' => 100,
    '#description' => t('Le pays'),
    '#required' => TRUE,
  );

  $form['date'] = array(
    '#type' => 'textfield',
    '#title' => t('Date de l\'évènement'),
    '#default_value' => variable_get('date', 'MARDI 21 MARS 2017'),
    '#size' => 50,
    '#maxlength' => 100,
    '#description' => t('La date de l\'évènement. Ex : MARDI 21 MARS 2017.'),
    '#required' => TRUE,
  );

  $form['heure'] = array(
    '#type' => 'textfield',
    '#title' => t('Heure de l\'évènement'),
    '#default_value' => variable_get('heure', '20h - 00h'),
    '#size' => 50,
    '#maxlength' => 100,
    '#description' => t('L\'heure de l\'évènement. Ex : 20h - 00h.'),
    '#required' => TRUE,
  );

  $form['premiere_couleur'] = array(
    '#type' => 'textfield',
    '#title' => t('Valeur de la couleur principale'),
    '#default_value' => variable_get('premiere_couleur', '#000000'),
    '#size' => 30,
    '#maxlength' => 30,
    '#description' => t('Code couleur : rgb, hexa ou code CSS'),
    '#required' => TRUE,
    );

  $form['deuxieme_couleur'] = array(
    '#type' => 'textfield',
    '#title' => t('Valeur de la couleur secondaire'),
    '#default_value' => variable_get('deuxieme_couleur', '#000000'),
    '#size' => 30,
    '#maxlength' => 30,
    '#description' => t('Code couleur : rgb, hexa ou code CSS'),
    '#required' => TRUE,
  );

  $form['programme'] = array(
    '#type' => 'textarea',
    '#title' => t('Programme fixe de la soirée'),
    '#default_value' => variable_get('programme', 'dorf'),
    '#size' => 400,
    '#maxlength' => 1000,
    '#description' => t('titre | localisation | description'),
    '#required' => TRUE,
  );

  $form['continu'] = array(
    '#type' => 'textarea',
    '#title' => t('Programme continu de la soirée'),
    '#default_value' => variable_get('continu', 'dorf'),
    '#size' => 400,
    '#maxlength' => 1000,
    '#description' => t('titre | localisation | description'),
    '#required' => TRUE,
  );

  $form['captcha'] = array(
    '#type' => 'textfield',
    '#title' => t('Clé captcha'),
    '#default_value' => variable_get('captcha', 'David guetta'),
    '#size' => 50,
    '#maxlength' => 100,
    '#description' => t('Rentrez une clé.'),
    '#required' => TRUE,
  );

  $form = system_settings_form($form);
  $form['#submit'][] = 'bacchanight_submit';

  return $form;
}

function bacchanight_submit($form, $form_state) {

    $file = fopen("sites/all/modules/bacchanight/templates/content/config.php", "w");

    $current_string = "<?php \n\n";


     $current_string .= "\$titre = \"".variable_get('titre', 3)."\";\n";
     $current_string .= "\$email = \"".variable_get('mail', 3)."\";\n";
     $current_string .= "\$phone = \"".variable_get('numero_telephone', 3)."\";\n";
     $current_string .= "\$street = \"".variable_get('adresse', 3)."\";\n";
     $current_string .= "\$zipcode = \"".variable_get('zipcode', 3)."\";\n";
     $current_string .= "\$city = \"".variable_get('ville', 3)."\";\n";
     $current_string .= "\$country = \"".variable_get('pays', 3)."\";\n";
     $current_string .= "\$date = \"".variable_get('date', 3)."\";\n";
     $current_string .= "\$address = \""
                        ."<p>\"."
                        ."\$street."
                        ."\"<br>\"."
                        ."\$zipcode."
                        ."\" \"."
                        ."\$city."
                        ."\", \"."
                        ."\$country."
                        ."\"</p>"
                        ."\";\n";
     $current_string .= "\$heure = \"".variable_get('heure', 3)."\";\n";
     $current_string .= "\$color1 = \"".variable_get('premiere_couleur', 3)."\";\n";
     $current_string .= "\$color2 = \"".variable_get('deuxieme_couleur', 3)."\";\n";
     $current_string .= "\$captcha = \"".variable_get('captcha', 3)."\";\n";

     //Création du xml
     $current_string .= "\$programme = \""."<?xml version='1.0' standalone='yes'?>"."\n";
     $current_string .= "<ListeProgramme>"."\n";
     $current_string .= "<programme>"."\n";

     $programme = variable_get('programme', 3);

     $explodeEndLine = explode("\n", $programme);
     $j=0;
     for($i = 0; $i<sizeof($explodeEndLine); $i++){
        $explodePipe = explode("|", $explodeEndLine[$i]);
        $current_string .= "<event>"."\n";
        $current_string .= "<location>".trim($explodePipe[$j], " ")."</location>"."\n";
        $current_string .= "<titre>".trim($explodePipe[$j+1], " ")."</titre>"."\n";
        $current_string .= "<description>".rtrim(trim($explodePipe[$j+2], " "))."</description>"."\n";
        $current_string .= "</event>"."\n";
     }

     $current_string .= "</programme>"."\n";

     $current_string .= "<programme>"."\n";

     $continu = variable_get('continu', 3);

     $explodeEndLine = explode("\n", $continu);
     $j=0;
     for($i = 0; $i<sizeof($explodeEndLine); $i++){
        $explodePipe = explode("|", $explodeEndLine[$i]);
        $current_string .= "<event>"."\n";
        $current_string .= "<location>".trim($explodePipe[$j], " ")."</location>"."\n";
        $current_string .= "<titre>".trim($explodePipe[$j+1], " ")."</titre>"."\n";
        $current_string .= "<description>".rtrim(trim($explodePipe[$j+2], " "))."</description>"."\n";
        $current_string .= "</event>"."\n";
     }

     $current_string .= "</programme>"."\n";

     $current_string .= "</ListeProgramme>"."\"".";"."\n";

     $current_string .= "\n?>";

     fwrite($file, $current_string);

     fclose($file);

}


function machin(){
    $tabvar = array(
        'titre' => variable_get('titre', 3),
        'email' => variable_get('mail', 3),
        'phone' => variable_get('numero_telephone', 3),
        'street' => variable_get('adresse', 3),
        'zipcode' => variable_get('zipcode', 3),
        'city' => variable_get('ville', 3),
        'country' => variable_get('pays', 3),
        'date' => variable_get('date', 3),
        'heure' => variable_get('heure', 3),
        'color1' => variable_get('premiere_couleur', 3),
        'color2' => variable_get('deuxieme_couleur', 3),
        'programme' => variable_get('programme', 3),
        'continu' => variable_get('continu', 3),
        'captcha' => variable_get('captcha')
    );

    return $tabvar;
}

function param_manager($event = NULL) {


$tabvar = array(
    'titre' => variable_get('titre', 3),
    'email' => variable_get('mail', 3),
    'phone' => variable_get('numero_telephone', 3),
    'street' => variable_get('adresse', 3),
    'zipcode' => variable_get('zipcode', 3),
    'city' => variable_get('ville', 3),
    'country' => variable_get('pays', 3),
    'date' => variable_get('date', 3),
    'heure' => variable_get('heure', 3),
    'color1' => variable_get('premiere_couleur', 3),
    'color2' => variable_get('deuxieme_couleur', 3),
    'programme' => variable_get('programme', 3),
    'continu' => variable_get('continu', 3),
    'captcha' => variable_get('captcha')
);

  return theme('bacchanight',array('results' => $tabvar));
}



function bacchanight_theme() {
    $t=machin();
  return array(
      'bacchanight' => array(
        'template' => 'templates/html--bacchanight',
        //manquel'argument pour que ce soit html et pas node
      'variables' => array(
        'results' => $t,
      ),
     ),
  );
}
